steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: [ 'build', '-t', 'gcr.io/psyched-age-295904/concrete-test', '.' ]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/concrete-test/psyched-age-295904:latest"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/kubectl"
  args: ["apply", "-f", "${_DOCKERFILE}/deployments/k8s/"]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east4-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'